#  Introduction to TensorFlow

TensorFlow is powerful but rather complex. It might look intimidating at first, but with a little practice you will quickly be more at ease with it.

Let's start by importing the tensorflow and numpy libraries.

In [1]:
import tensorflow as tf
import numpy as np

/home/alexander/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/alexander/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/alexander/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/alexander/.local/lib/python3.6/site-packages/tensorflow/python/framework/dty

## Tensors

All the data structures in TensorFlow are stored in "tensors" which are n-dimensional arrays. Some examples below.

In [2]:
n_row = 3; n_col = 4; # number of rows and columns

## Tensors with fixed values,
tsr = tf.zeros([n_row, n_col])
#tsr = tf.ones([n_row, n_col])
#tsr = tf.fill([n_row, n_col], 3.14)
#tsr = tf.constant([1,2,3])

## with same shape,
tsr_like = tf.zeros_like(tsr)
#tsr_like = tf.ones_like(tsr)

## from sequences,
tsr_seq = tf.linspace(start=1.0, stop=3.0, num=3)
#tsr_seq = tf.range(start=6, limit=15, delta=3)

## with random values generator (be careful!)
tsr_rnd = tf.random_uniform([n_row, n_col], minval=0, maxval=1)
#tsr_rnd = tf.random_normal([n_row, n_col], mean=0.0, stddev=1.0)
#tsr_rnd = tf.truncated_normal([n_row, n_col], mean=0.0, stddev=1.0)
#tsr_rnd = tf.random_shuffle(input_tensor)
#tsr_rnd = tf.random_crop(input_tensor, crop_size)
#tsr_rnd = tf.random_crop(my_image, [height/2, width/2,3])

## from a numpy array
np_ar = np.array([[1.0, 2.0],[3.0, 4.0]]) # a numpy array
tsr_from_np = tf.convert_to_tensor(np_ar)

If you try to display a tensor as in Matlab, R, or numpy, you might be disappointed. (No worry, we will see how to display a tensor's values a bit later.)

**Remark:** there exists an execution mode in which TF behaves more naturally, the so-called *eager execution*, it will be the default mode in v2.

In [3]:
print("A numpy array:\n", np_ar, "\n")
print("A tensor:\n", tsr_from_np, "\n")

A numpy array:
 [[1. 2.]
 [3. 4.]] 

A tensor:
 Tensor("Const:0", shape=(2, 2), dtype=float64) 



Remark that all tensors have unique names. It is done automatically if you do not pass a name.

In [4]:
tsr_named = tf.zeros([2,2], name="mytensor")
print("I named this tensor:\n", tsr_named)
# Check for yourself what is happenning bellow if you try to give the same name to a tensor!
#tsr_named2 = tf.zeros([2,2], name="mytensor")
#print("I also named this tensor:\n", tsr_named2)

I named this tensor:
 Tensor("mytensor:0", shape=(2, 2), dtype=float32)


## Placeholders and variables

Placeholders are the *input* tensors to feed in the data, they are the $X_i$ and $Y_i$ observations. Variables are the *parameter* tensors to be optimized, they are the $\theta$.

In [14]:
x = tf.placeholder(name='x', shape=(None,2), dtype='float32') # need to specify the shape and data type
w = tf.Variable(name='w', initial_value=tf.fill([2,1],1.0), dtype='float32') # need to specify the initial_value 

## Graphs and sessions

A computational graph defines the operations that you specified in your code. It does not compute anything, it does not store values. An operation is added to a graph forever!

A session allows to execute (part of) graphs. It allocates resources (on one or more machines) and store intermediate results and variable values.

In [15]:
sess = tf.Session() # create a session
sess.run(tf.global_variables_initializer()) # variables ALWAYS need to be initialized

## (finally) display some tensor values!
print("Here is a tensor:\n", sess.run(tsr_from_np), "\n")
print("Here is another one:\n", sess.run(tsr_like), "\n")
print("The random tensor:\n", sess.run(tsr_rnd), "\n")
print("The random tensor again (surprise!):\n", sess.run(tsr_rnd), "\n") 

Here is a tensor:
 [[1. 2.]
 [3. 4.]] 

Here is another one:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

The random tensor:
 [[0.45383823 0.43326867 0.91634655 0.5853101 ]
 [0.39325774 0.36289895 0.90962124 0.12327242]
 [0.42637563 0.9781616  0.22612023 0.3724923 ]] 

The random tensor again (surprise!):
 [[0.34015954 0.5597311  0.6307229  0.1610514 ]
 [0.54381275 0.82062304 0.52373075 0.4953643 ]
 [0.27338898 0.44805825 0.68479216 0.24344456]] 



Tensorflow creates by default a graph, but you can be specific when using graphs and sessions.

In [11]:
# Create a new graph and add operations to it
graph = tf.Graph()
with graph.as_default():
    variable = tf.Variable(3.14, name='myvar')
    initializer = tf.global_variables_initializer()
    assign = variable.assign(variable**2)

with tf.Session(graph=graph) as sess:
    sess.run(initializer)
    print("before:\t", sess.run(variable))
    sess.run(assign)
    print("after:\t", sess.run(variable))

before:	 3.14
after:	 9.859601


It is possible to have  can have a first *rough* look at what is inside the Graphs as follows.

In [8]:
#print("The default graph:\n", tf.get_default_graph().get_operations(), "\n")
print("The small graph we build just above:\n", graph.get_operations(), "\n")

# you can also save the graph in *.json or *.txt format which is slightly more readable
import os
tf.train.write_graph(graph, os.getcwd(), 'graph.json')

The small graph we build just above:
 [<tf.Operation 'myvar/initial_value' type=Const>, <tf.Operation 'myvar' type=VariableV2>, <tf.Operation 'myvar/Assign' type=Assign>, <tf.Operation 'myvar/read' type=Identity>, <tf.Operation 'init' type=NoOp>, <tf.Operation 'pow/y' type=Const>, <tf.Operation 'pow' type=Pow>, <tf.Operation 'Assign' type=Assign>] 



'/home/alexander/Classwork/MLFIN/graph.json'

Now let's input some data into our graph. This is done using a dictionnary.

In [16]:
## put random data into a dict
x_np = np.random.rand(5,2)
mydict = {'x:0' : x_np}

## get the 'x:0' tensor from the default computational graph, in case 'x' was re-assigned in between
x = tf.get_default_graph().get_tensor_by_name("x:0")
## it is a bit different for variables
w = [v for v in tf.global_variables() if v.name == "w:0"][0] 
                        
## call operation
print("Random data:\n", x_np, "\n")
print("Random data:\n", x_np, "\n")
print("Load data and use variable:\n", sess.run(tf.matmul(x,w), feed_dict=mydict), "\n") # Note the second argument

Random data:
 [[0.71888959 0.29174016]
 [0.39082558 0.44942791]
 [0.43826155 0.66566156]
 [0.47617649 0.8929768 ]
 [0.39654424 0.53329322]] 

Random data:
 [[0.71888959 0.29174016]
 [0.39082558 0.44942791]
 [0.43826155 0.66566156]
 [0.47617649 0.8929768 ]
 [0.39654424 0.53329322]] 

Load data and use variable:
 [[1.0106298 ]
 [0.8402535 ]
 [1.1039231 ]
 [1.3691533 ]
 [0.92983747]] 



## Function operations and matrix computations

Standard functions and basic matrix operations are available. 

In [17]:
## create some matrices
A = tf.diag([1.0, 2.0, 3.0]) # make a diagonal matrix from a list of floats
B = tf.fill([2,3], 5.0)

## do stuffs
print("Multiply by a scalar:\n", sess.run(2.0 * A), "\n")
print("Matrix multiplication:\n", sess.run(tf.matmul(B, A)), "\n")
#print("Matrix transpose:\n", sess.run(tf.transpose(A)), "\n")
#print("Matrix determinant:\n", sess.run(tf.matrix_determinant(A)), "\n")
#print("Matrix inverse:\n", sess.run(tf.matrix_inverse(A)), "\n")
#print("Cholesky decomposition:\n", sess.run(tf.cholesky(A)), "\n")
## and many more...
#print("Functions 'tf.linalg':\n", [fun for fun in dir(tf.linalg) if not str(fun).startswith('_', 0,1)], "\n")

## basic math functions are applied element-wise to tensors
#print("Functions in 'tf.math':\n", [fun for fun in dir(tf.math) if not str(fun).startswith('_', 0,1)], "\n")

Multiply by a scalar:
 [[2. 0. 0.]
 [0. 4. 0.]
 [0. 0. 6.]] 

Matrix multiplication:
 [[ 5. 10. 15.]
 [ 5. 10. 15.]] 

